### ISSUE TITLE
max-width issue

### ISSUE THREAD

**Issue by C-Ezra-M** [pokemoncentral/wiki-styles#14]
The classes `max-width-__-auto`, where `__` indicates any of `xl`, `lg`, `md`, `sm` or `xs`, have an invalid `max-width: auto` property. The correct value is `none` according to the spec: https://developer.mozilla.org/en-US/docs/Web/CSS/max-width#values

`width` and `min-width` indeed support `auto` instead of `none`:
- https://developer.mozilla.org/en-US/docs/Web/CSS/width#values
- https://developer.mozilla.org/en-US/docs/Web/CSS/min-width#values

**Comment by flavio-a** [comment]
Thanks for the report, I'm fixing this right now (and also sorry for the delay in the response ^^').
